### ISSUE TITLE
Restoring a working Docker image

### ISSUE THREAD

**Issue by cfq20** [GetStream/Winds#116]
Hi, 

I would like to run winds from a Docker container. The official image build currently is failing on Docker Hub and this is because of a reference in both Dockerfile and docker-entrypoint.sh to the missing file process.json. I changed this reference to process_prod.json and successfully rebuilt the image, however when I run the container I now get a different error which causes it to stop. This is the end of the log from the running container, obtained with `docker logs -tf winds` (where 'winds' is the name of my winds container:
```
2017-10-25T10:46:46.342451741Z npm info ok 
2017-10-25T10:46:47.777307764Z /home/app/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:281
2017-10-25T10:46:47.777380823Z               throw e;
2017-10-25T10:46:47.777447818Z               ^
2017-10-25T10:46:47.777464068Z 
2017-10-25T10:46:47.777503124Z `include-all` attempted to `require(/home/app/config/passport.js)`, but an error occurred:: 
2017-10-25T10:46:47.777519123Z Details:TypeError: JwtStrategy requires a secret or key
2017-10-25T10:46:47.777556121Z     at new JwtStrategy (/home/app/node_modules/passport-jwt/lib/strategy.js:29:15)
2017-10-25T10:46:47.777571068Z     at Object.<anonymous> (/home/app/config/passport.js:62:14)
2017-10-25T10:46:47.777607590Z     at Module._compile (module.js:570:32)
2017-10-25T10:46:47.777622646Z     at Object.Module._extensions..js (module.js:579:10)
2017-10-25T10:46:47.777658460Z     at Module.load (module.js:487:32)
2017-10-25T10:46:47.777673592Z     at tryModuleLoad (module.js:446:12)
2017-10-25T10:46:47.777706450Z     at Function.Module._load (module.js:438:3)
2017-10-25T10:46:47.777721134Z     at Module.require (module.js:497:17)
2017-10-25T10:46:47.777753963Z     at require (internal/module.js:20:19)
2017-10-25T10:46:47.777768989Z     at /home/app/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:271:33
2017-10-25T10:46:47.777804538Z     at Array.forEach (native)
2017-10-25T10:46:47.777820668Z     at _recursivelyIncludeAll (/home/app/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:174:11)
2017-10-25T10:46:47.777871885Z     at includeAll (/home/app/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:292:5)
2017-10-25T10:46:47.777887417Z     at helpBuildDictionary (/home/app/node_modules/sails/node_modules/include-all/lib/help-build-dictionary.js:43:15)
2017-10-25T10:46:47.777926610Z     at Function.module.exports.aggregate (/home/app/node_modules/sails/node_modules/include-all/index.js:101:10)
2017-10-25T10:46:47.777941557Z     at Array.loadOtherConfigFiles (/home/app/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
2017-10-25T10:46:47.777977169Z     at /home/app/node_modules/sails/node_modules/async/lib/async.js:591:38
2017-10-25T10:46:47.777992059Z     at _arrayEach (/home/app/node_modules/sails/node_modules/async/lib/async.js:85:13)
2017-10-25T10:46:47.778118634Z     at Object.async.auto (/home/app/node_modules/sails/node_modules/async/lib/async.js:552:9)
2017-10-25T10:46:47.778138455Z     at Hook.loadUserConfig (/home/app/node_modules/sails/lib/hooks/moduleloader/index.js:245:13)
2017-10-25T10:46:47.778180866Z     at Hook.wrapper [as loadUserConfig] (/home/app/node_modules/@sailshq/lodash/lib/index.js:3250:19)
2017-10-25T10:46:47.778196574Z     at Hook.loadModules (/home/app/node_modules/sails/lib/hooks/userconfig/index.js:41:27)
2017-10-25T10:46:55.617256740Z PM2 Daemon is dead
```
It appears a secret or key is missing somewhere, but since I don't know this code and I am not a JS expert, I would appreciate any directions for fixing it. I would be happy to fix the code, test the Docker container again and submit a PR, if I manage to make it work.

This issue with the Docker image was reported before in issue #107 .

**Comment by cfq20** [comment]
After giving it another look, I realised it is necessary to register an account on getstream.io to get an app ID, API key and secret and an analytics token from the dashboard and to set required environment variables in order for Winds to work. 

The error above indicates just that, so this issue can be closed now.
