### ISSUE TITLE
Does Winds 1.0 still works?

### ISSUE THREAD

**Issue by Yakito** [GetStream/Winds#123]
Hi, Happy new year!

I know Winds 2.0 is under development, but I would like to try out Winds 1.0 in the meantime. The problem is that after following every step I still can not make it work. I found some issues during the installation, which I solved, but then when I try to launch the app and redirect my browser it fails.

Does anyone know if Winds 1.0 still works? Any tips on how to make it work?

Thanks!

**Comment by nparsons08** [comment]
Hey there @Yakito, lead maintainer here. Winds 1.0 definitely still works if the application is set up correctly. I can't offer support for it though as 2.0 is underway and taking up a lot of my time. If there's something super specific you're having trouble with, I'll do my very best to help you out.

**Comment by Yakito** [comment]
Thanks Nick ,I will try the installation again and if I got a roadblock
I'll post it in case you can help.

**Comment by Yakito** [comment]
Hey @nparsons08 , finally I managed to install the app (the install procedure is slightly different than the one on the docs) but I got errors when adding the starter feeds. I bypassed those errors by creating an account with Facebook (again, slightly different than just adding the credentials) and finally was able to log in.

Now the problem I am having is that I am not able to add any feed. It doesn't matter which feed I try to add I always get "FEED MISSING"

Also when I check the logs, I see the following warnings

```
info: sails-hook-webpack2: Watching for changes...
info: sails-hook-webpack2: Build complete. Hash: 4a663e967eec3b77f586, Time: 5169ms
warn: Error: data and salt arguments required
    at /home/ubuntu/Winds/node_modules/bcrypt/bcrypt.js:114:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
warn: Error (E_UNKNOWN) :: Encountered an unexpected error
: data and salt arguments required
    at /home/ubuntu/Winds/node_modules/bcrypt/bcrypt.js:114:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Details:  Error: data and salt arguments required

warn: Error (E_UNKNOWN) :: Encountered an unexpected error
: data and salt arguments required
    at /home/ubuntu/Winds/node_modules/bcrypt/bcrypt.js:114:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Details:  Error: data and salt arguments required
```

And when I tried to install the starter feeds, I got the same error as this thread https://github.com/GetStream/Winds/issues/121

```
info: configuring mail service to use sendgrid backend
info: Starting to load the initial data...
info: inserted topic Design
info: inserted topic Startups
info: inserted topic Programming
info: inserted topic Gaming
info: inserted topic LifeHacks
info: inserted topic Venture Capital
info: inserted topic AI & Machine Learning
info: inserted topic News
info: inserted topic VR
info: inserted all topics, feeds are up next
info: inserted site dribbble.com
/home/ubuntu/Winds/load_initial_data.js:106
                        sails.sentry.captureMessage(err)
                                    ^

TypeError: Cannot read property 'captureMessage' of undefined
    at /home/ubuntu/Winds/load_initial_data.js:106:37
    at wrapper (/home/ubuntu/Winds/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/home/ubuntu/Winds/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/ubuntu/Winds/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at /home/ubuntu/Winds/node_modules/waterline/lib/waterline/query/composite.js:71:25
    at wrapper (/home/ubuntu/Winds/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/home/ubuntu/Winds/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/ubuntu/Winds/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at /home/ubuntu/Winds/node_modules/waterline/lib/waterline/query/dql/create.js:73:23
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:726:13
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:264:21
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:723:17
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:167:37
    at /home/ubuntu/Winds/node_modules/waterline/lib/waterline/query/validate.js:79:23
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:726:13
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:264:21
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:723:17
    at /home/ubuntu/Winds/node_modules/waterline/node_modules/async/lib/async.js:167:37
    at _afterValidating (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/query/validate.js:53:20)
    at allValidationsChecked (/home/ubuntu/Winds/node_modules/waterline/lib/waterline/core/validations.js:265:12)
```

Any tips on why it might be preventing me of adding feeds?
Thanks in advance

**Comment by nparsons08** [comment]
Hello, have you configured your feeds properly on GetStream.io?

**Comment by Yakito** [comment]
Hello Nick, thanks for your time. I think I did, but if you think that might be the error I will try creating a new account on getstream and starting all over again.

I'll get you posted.
